### ISSUE TITLE
Basic Jumpstart D8 Theme

### ISSUE THREAD

**Issue by tsui1** [SU-SWS/stanford_basic#1]
Aiming for common elements, general palette - nav, headings, containers. 

- Where does navigation live, how does it look
- Full width/bleed layouts
- Paragraph types functionality
- Page types

What can we take from what we have now? We are also using panels now, how does that affect our workflow?

Panel area is below the masthead, and above the footer.

**Comment by tsui1** [comment]
Want to make sure everyone has a local D8 environment. @sherakama has a package that can be used to install for everyone.

**Comment by tsui1** [comment]
Want to nail down header+footer regions

**Comment by sherakama** [comment]
Done in version 8.x-4.x
