### ISSUE TITLE
Twig template not found after installation and set as default

### ISSUE THREAD

**Issue by masifi** [SU-SWS/stanford_basic#153]
**Describe the bug**
`Uncaught PHP Exception Twig\Error\LoaderError: "Template "@basic-dist/decanter/components/brand-bar/brand-bar.twig" is not defined in "themes/stanford_basic/templates/page.html.twig" at line 1."  at drupal/vendor/twig/twig/src/Loader/ChainLoader.php line 142`

**To Reproduce**
1. I just installed the theme and built the libraries using npm.
2. After I enabled the theme this is what happen in frontend a white screen with "The website encountered an unexpected error. Please try again later."
3. However, I changed the path "@basic-dist/decanter/.." with "@THEME_NAME/dist/decanter/.." it doesn't load the templates from dest/decant directory.

**Note**
By the way, I cleared the cache many times with different scenarios but it wouldn't help.

I appreciate your help to overcome this problem.

**Comment by sherakama** [comment]
I suspect this was due to missing the `components` module? Just recently there was a commit to Drupal core to allow themes to declare module dependencies. We have a comment in our info.yml file to enable this and should do so.

**Comment by masifi** [comment]
Thank you so much for your clarification.

**Comment by sherakama** [comment]
The work is in progress here and will be merged down and available when Drupal 8.9 is available.

https://github.com/SU-SWS/stanford_basic/pull/154
