### ISSUE TITLE
Content Type: Article Page

### ISSUE THREAD

**Issue by sherakama** [SU-SWS/stanford_basic#17]
- Content type with paragraphs

**Comment by sherakama** [comment]
- Create an article content type and attach only the paragraph types that should be used to it.
- Bundle as a feature. 
- Style the general look of the page (not the paragraphs themselves)

**Comment by tsui1** [comment]
Limited to editorial style paragraphs (imagery, text treatments, pull quotes, etc). No menus, heros, etc.
