### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by tsui1** [SU-SWS/stanford_basic#2]
Where does live, what does it look like

**Comment by sherakama** [comment]
![screen shot 2017-03-24 at 11 18 54 am](https://cloud.githubusercontent.com/assets/550602/24308068/cdb577d8-1083-11e7-93d3-3d34b2155c04.png)
![screen shot 2017-03-24 at 11 19 26 am](https://cloud.githubusercontent.com/assets/550602/24308069/cdb60f7c-1083-11e7-97f9-1f1832d92754.png)

Will need to talk through scale, hierarchy, and state

**Comment by tsui1** [comment]
Most SOE examples might not be the best, since it's for a very specific use case. What about pulling from https://sites.stanford.edu/ipaw-big-design/

**Comment by sherakama** [comment]
![screen shot 2017-03-24 at 11 35 14 am](https://cloud.githubusercontent.com/assets/550602/24308624/fa15fd96-1085-11e7-96f9-f852ce5355ac.png)

**Comment by sherakama** [comment]
First pass completed, second pass when we get DEC-71 merged.
