### ISSUE TITLE
Advanced Site Title lockups

### ISSUE THREAD

**Issue by tsui1** [SU-SWS/stanford_basic#39]
Need a discovery on how to improve the authoring UX of building site title lockups for D8 theme.

See previous lockups style guide: 
https://docs.google.com/document/d/14_92mZHRocYWwFQfMWdTz5kQpT1QoSGj4AazAsRM5mc/edit

and old Stanford_framework issue:
https://github.com/SU-SWS/stanford_framework/issues/162

**Comment by sherakama** [comment]
This has been implemented and merged in #82
